[package]
name = "paramp"
version = "1.0.0"
authors = ["cetra3 <peter@parashift.com.au>"]

[dependencies]
zip = "0.1"
yaml-rust = "*"
clap = "*"
hyper = "*"
rust-crypto = "*"
rustc-serialize = "*"
semver = "*"
regex = "*"
lazy_static = "*"
toml = "*"
memmap = "*"
